### PR TITLE
Add Relative linking

### PR DESCRIPTION
**Pull request by baseplate-admin**
Hi there,

I ran into an error when i link to `search.html` from my markdown codes as it doesn't work properly. 

This PR aims to fix that

### CODE REVIEW

**Comment by aleylara** [comment]
I haven't been able to reproduce the errors with the pages generated using the sample `pelicanconf.py` for the demo site. 
I was able to generate internal links using the syntax 

`[search](search.html)` 

`[How to Install]({filename}/Software/article-one.md)`

**Comment by baseplate-admin** [comment]
>  I was able to generate internal links using the syntax

Hi there,

This is weird as i was getting an error from my end. I will recheck and report back

**Comment by baseplate-admin** [comment]
Hi @aleylara,

There was recent changes to https://github.com/pelican-plugins/search which results in 
```bash
[16:56:48] WARNING  The SEARCH_HTML_SELECTOR setting is deprecated and will be removed in a future version. Use the STORK_INPUT_OPTIONS setting instead.                                                               log.py:91
           WARNING  SEARCH_MODE = output is deprecated and will be removed in a future version. Use the STORK_INPUT_OPTIONS setting instead.   
```

**Comment by aleylara** [comment]
Hi @baseplate-admin,
Noted, thank you.

**Pull request closed without merging**
